FROM node:12

WORKDIR /usr/src/app

COPY package.json ./
COPY . ./

RUN npm install
RUN pwd
RUN ls -la
RUN npm run types

# RUN npm install pm2 -g

# RUN npm run build

# COPY ./dist .

EXPOSE 8080

# CMD ["pm2-runtime","server.js"]
CMD ["npm","run", "server:start:watch"]